//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleAutomation
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSession
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblSession()
        {
            this.tblSessionEmpLinks = new HashSet<tblSessionEmpLink>();
        }
    
        public System.Guid SessionID { get; set; }
        public string sessionCode { get; set; }
        public string sessionName { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<System.Guid> CourseID { get; set; }
        public Nullable<System.DateTime> SessionCreationDate { get; set; }
        public string sessionStatus { get; set; }
        public Nullable<int> fk_statusID { get; set; }
    
        public virtual tblCourses tblCours { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSessionEmpLink> tblSessionEmpLinks { get; set; }
        public virtual tblSessionStatus tblSessionStatu { get; set; }
    }
}
